# Generated by Django 6.0.5 on 2026-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sacramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.SlugField(unique=True)),
                ('requiere_padrinos', models.BooleanField(default=True)),
                ('requiere_curso', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sacramento',
                'verbose_name_plural': 'Sacramentos',
                'ordering': ['nombre'],
            },
        ),
    ]
