# Generated by Django 6.0.5 on 2026-05-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacramento',
            name='descripcion',
            field=models.TextField(unique=True),
        ),
    ]
