# Generated by Django 6.0.5 on 2026-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0002_alter_sacramento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feligres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feligres',
                'verbose_name_plural': 'Feligreses',
                'ordering': ['nombres', 'apellidos'],
            },
        ),
    ]
