# Generated by Django 6.0.5 on 2026-05-31 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0003_feligres'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSacramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sacramento', models.DateField()),
                ('lugar', models.TextField()),
                ('sacerdote', models.CharField()),
                ('numero_acta', models.CharField(unique=True)),
                ('libro', models.CharField()),
                ('folio', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feligres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registro_sacramentos_feligreses', to='sacramentos.feligres')),
                ('sacramento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registro_sacramentos', to='sacramentos.sacramento')),
            ],
            options={
                'verbose_name': 'Registro_sacramento',
                'verbose_name_plural': 'Registro_sacramentos',
                'ordering': ['sacerdote', 'feligres', 'sacramento'],
            },
        ),
    ]
