# Generated by Django 6.0.5 on 2026-05-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0004_registrosacramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosacramento',
            name='observaciones',
            field=models.TextField(default=True),
        ),
    ]
