# Generated by Django 6.0.5 on 2026-06-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0005_registrosacramento_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField()),
                ('apellidos', models.CharField()),
                ('cedula', models.CharField()),
                ('telefono', models.CharField()),
                ('parentesco', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registro_sacramento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='padrinos', to='sacramentos.registrosacramento')),
            ],
            options={
                'verbose_name': 'Padrino',
                'verbose_name_plural': 'Padrinos',
                'ordering': ['nombres'],
            },
        ),
    ]
