# Generated by Django 6.0.5 on 2026-06-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sacramentos", "0006_padrinos"),
    ]

    operations = [
        migrations.CreateModel(
            name="CursoSacramental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_curso", models.CharField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("estado", models.CharField()),
                ("responsable", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feligres",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curso_sacramental_feligreses",
                        to="sacramentos.feligres",
                    ),
                ),
                (
                    "sacramento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curso_sacramental",
                        to="sacramentos.sacramento",
                    ),
                ),
            ],
            options={
                "verbose_name": "CursoSacramental",
                "verbose_name_plural": "CursosSacramentales",
                "ordering": ["nombre_curso"],
            },
        ),
    ]
